server:
  port: 80

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 默认数据库连接池 配置
#    hikari:
#      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
#      connection-timeout: 30000
#      # 最小连接数
#      minimum-idle: 5
#      # 最大连接数
#      maximum-pool-size: 15
  servlet:
    multipart:
      # 支持的最大上传文件
      max-file-size: 100MB
      max-request-size: 1000MB
  redis:
    host: 127.0.0.1
    port: 6379
  jackson:
    # 格式化后台返前台时 的 日期格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT%2B8


logging:
  level:
    root: INFO

mybatis:
  configuration:
    # 控制台输出日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰，开启后，只要数据库字段和对象属性名字母相同，无论中间加多少下划线都可以识别
    map-underscore-to-camel-case: true
  # mapper.xml 不在 resourece 目录下时，需要配置路径
  mapper-locations: classpath:com/shakag/mapper/xml/*.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      propertyFormat: "\"%s\"" # 给sql 别名加上双引号，例如 select name as "myName" from table;

knife4j:  # Swagger 增强
  enable: true